Vagrant.configure(2) do |config|
  # config.vm.box = "centos/7"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["sharedfolder", "add", :id, "--name", "salt", "--hostpath", File.expand_path("./salt", File.dirname(__FILE__)), "--automount"]
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.synced_folder "salt/roots/", "/srv/salt/"

  config.vm.provision "shell", inline: "ln -nfs /media/sf_salt /srv/salt"

  config.vm.provision :salt do |salt|
    salt.masterless = true
    # salt.minion_config = "salt/minion.yml"
    salt.run_highstate = true
    salt.colorize = true
    salt.log_level = 'info'
  end
end